// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RR_Nueva_Naturaleza.DAL;

#nullable disable

namespace RR_Nueva_Naturaleza.Migrations
{
    [DbContext(typeof(RR_Nueva_NaturalezaContext))]
    [Migration("20250926052250_IsUnique-Checklist")]
    partial class IsUniqueChecklist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.ActuatorMode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAutoMode")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsAuto")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("ActuatorModes");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserId");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.ChecklistDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChecklistHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DispositivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("MedicionManual")
                        .HasColumnType("float");

                    b.Property<double?>("MedicionSensor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistHeaderId");

                    b.HasIndex("DispositivoId");

                    b.ToTable("ChecklistDetails");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.ChecklistHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ChecklistHeaders");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.ControlRuleActuator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ControlRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TriggerType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ControlRuleId");

                    b.HasIndex("DeviceId");

                    b.ToTable("ControlRuleActuators");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.ControlRules", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Max")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Min")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("ControlRules");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Device_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("Device_StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Device_TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SN")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("System_TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Device_Name")
                        .IsUnique();

                    b.HasIndex("Device_StatusId");

                    b.HasIndex("Device_TypeId");

                    b.HasIndex("System_TypeId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.Device_Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State_Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("State_Name")
                        .IsUnique();

                    b.ToTable("Device_States");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.Device_Type", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Device_Type_Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Device_Type_Name")
                        .IsUnique();

                    b.ToTable("Device_Types");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ImpactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("System_TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Visto")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ImpactId");

                    b.HasIndex("System_TypeId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.Impact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Impact_Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Impact_Type")
                        .IsUnique();

                    b.ToTable("Impacts");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.Measurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Measurement_TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Measurement_TypeId");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.Measurement_Type", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("Unit_MeasurementId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Unit_MeasurementId");

                    b.ToTable("Measurement_Types");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Rols");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.Property<int>("Minute")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.System_Type", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("System_Type_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("System_Type_Name")
                        .IsUnique();

                    b.ToTable("System_Types");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.Unit_Measurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Unit_Measurements");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id_Card")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Questions_Type")
                        .HasColumnType("int");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Id_Card")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.ActuatorMode", b =>
                {
                    b.HasOne("RR_Nueva_Naturaleza.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.Audit", b =>
                {
                    b.HasOne("RR_Nueva_Naturaleza.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RR_Nueva_Naturaleza.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.ChecklistDetail", b =>
                {
                    b.HasOne("RR_Nueva_Naturaleza.Models.ChecklistHeader", "ChecklistHeader")
                        .WithMany("Detalles")
                        .HasForeignKey("ChecklistHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RR_Nueva_Naturaleza.Models.Device", "Dispositivo")
                        .WithMany()
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistHeader");

                    b.Navigation("Dispositivo");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.ChecklistHeader", b =>
                {
                    b.HasOne("RR_Nueva_Naturaleza.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.ControlRuleActuator", b =>
                {
                    b.HasOne("RR_Nueva_Naturaleza.Models.ControlRules", "ControlRule")
                        .WithMany("ControlRuleActuators")
                        .HasForeignKey("ControlRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RR_Nueva_Naturaleza.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ControlRule");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.ControlRules", b =>
                {
                    b.HasOne("RR_Nueva_Naturaleza.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.Device", b =>
                {
                    b.HasOne("RR_Nueva_Naturaleza.Models.Device_Status", "Device_Status")
                        .WithMany()
                        .HasForeignKey("Device_StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RR_Nueva_Naturaleza.Models.Device_Type", "Device_Type")
                        .WithMany()
                        .HasForeignKey("Device_TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RR_Nueva_Naturaleza.Models.System_Type", "System_Type")
                        .WithMany()
                        .HasForeignKey("System_TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device_Status");

                    b.Navigation("Device_Type");

                    b.Navigation("System_Type");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.Event", b =>
                {
                    b.HasOne("RR_Nueva_Naturaleza.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RR_Nueva_Naturaleza.Models.Impact", "Impact")
                        .WithMany()
                        .HasForeignKey("ImpactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RR_Nueva_Naturaleza.Models.System_Type", "System_Type")
                        .WithMany()
                        .HasForeignKey("System_TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Impact");

                    b.Navigation("System_Type");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.Measurement", b =>
                {
                    b.HasOne("RR_Nueva_Naturaleza.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RR_Nueva_Naturaleza.Models.Measurement_Type", "Measurement_Type")
                        .WithMany()
                        .HasForeignKey("Measurement_TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Measurement_Type");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.Measurement_Type", b =>
                {
                    b.HasOne("RR_Nueva_Naturaleza.Models.Unit_Measurement", "Unit_Measurement")
                        .WithMany()
                        .HasForeignKey("Unit_MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit_Measurement");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.Schedule", b =>
                {
                    b.HasOne("RR_Nueva_Naturaleza.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.User", b =>
                {
                    b.HasOne("RR_Nueva_Naturaleza.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.ChecklistHeader", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("RR_Nueva_Naturaleza.Models.ControlRules", b =>
                {
                    b.Navigation("ControlRuleActuators");
                });
#pragma warning restore 612, 618
        }
    }
}
